// This file is auto-generated by @hey-api/openapi-ts

export const MessageSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;
