// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Message
 */
export type Message = {
    /**
     * Id
     */
    id?: string;
    /**
     * Message
     */
    message: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

export type MessagesGetMessagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/messages';
};

export type MessagesGetMessagesResponses = {
    /**
     * Response Messages-Get Messages
     *
     * Successful Response
     */
    200: Array<Message>;
};

export type MessagesGetMessagesResponse = MessagesGetMessagesResponses[keyof MessagesGetMessagesResponses];
